// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250104224418_AddVillaTable")]
    partial class AddVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupacy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Pool, Gym, Spa, Garden",
                            CreatedDate = new DateTime(2025, 1, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Labore exerci in sadipscing wisi enim facilisis dolores nulla exerci kasd magna voluptua et tation sanctus eleifend no amet consequat",
                            ImageUrl = "https://www.istockphoto.com/en/photo/moorish-castle-sintra-lisbon-in-portugal-gm1487324369-512841745",
                            Name = "Castle Villa",
                            Occupacy = 10,
                            Rate = 1000.0,
                            Sqft = 5000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Infinity Pool, Private Beach Access, Sauna, Outdoor Barbecue",
                            CreatedDate = new DateTime(2025, 1, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Sea-facing luxury villa with breathtaking views, perfect for a tranquil getaway.",
                            ImageUrl = "https://www.istockphoto.com/en/photo/moorish-castle-sintra-lisbon-in-portugal-gm1487324369-512841745",
                            Name = "Oceanview Villa",
                            Occupacy = 8,
                            Rate = 1500.0,
                            Sqft = 4000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Fireplace, Hiking Trails, Hot Tub, Ski-In/Ski-Out",
                            CreatedDate = new DateTime(2025, 1, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Nestled in the mountains, enjoy peaceful surroundings and a cozy atmosphere.",
                            ImageUrl = "https://www.istockphoto.com/en/photo/moorish-castle-sintra-lisbon-in-portugal-gm1487324369-512841745",
                            Name = "Mountain Retreat Villa",
                            Occupacy = 6,
                            Rate = 1200.0,
                            Sqft = 3500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Home Theater, Rooftop Deck, Smart Home Features, Wine Cellar",
                            CreatedDate = new DateTime(2025, 1, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Modern villa in the heart of the city with top-notch amenities and stunning interiors.",
                            ImageUrl = "https://www.istockphoto.com/en/photo/moorish-castle-sintra-lisbon-in-portugal-gm1487324369-512841745",
                            Name = "Urban Luxury Villa",
                            Occupacy = 5,
                            Rate = 2000.0,
                            Sqft = 3000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Private Pool, Hammocks, Outdoor Kitchen, Exotic Garden",
                            CreatedDate = new DateTime(2025, 1, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Experience tropical luxury with lush greenery and serene surroundings.",
                            ImageUrl = "https://www.istockphoto.com/en/photo/moorish-castle-sintra-lisbon-in-portugal-gm1487324369-512841745",
                            Name = "Tropical Paradise Villa",
                            Occupacy = 7,
                            Rate = 1800.0,
                            Sqft = 4500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
